### ISSUE TITLE
No _preloaded_transfer_ var found

### ISSUE THREAD

**Issue by cylwin** [orgrimarr/node-wetransfert#19]
Hello,

I got this error. Was working well until today. Maybe a wetransfer update. Do you have an idea ?

**Comment by orgrimarr** [comment]
Hello,
The wetransfer webpage changed. The transfer metadatas are no longer stored in a javascript objet directly accessibe in the page.
I will investigate

**Comment by cylwin** [comment]
I found the issue.. I'm making a PR

**Comment by orgrimarr** [comment]
Thanks for your contribution !
I released the 2.3.1 of wetransfert wich includes your download fix and an upload fix
