### ISSUE TITLE
Don't working anymore

### ISSUE THREAD

**Issue by cylwin** [orgrimarr/node-wetransfert#22]
Hello,

This time I have no idea where the problem is :

This is a log dump :

`DEBUG=wetransfert:* node helpers/wetransfer.js
  wetransfert:utils wetransfer API version: v4 +0ms
  wetransfert:utils isValidWetransfertUrl: true +79ms
  wetransfert:getinfos URLObject URL {
  href: 'https://wetransfer.com/downloads/068f46823c14ad9c3b5ef39d0f01f90120210504211103/7924157e91f9eff675d18ac63fcc23b820210504211117/ecbda7',
  origin: 'https://wetransfer.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'wetransfer.com',
  hostname: 'wetransfer.com',
  port: '',
  pathname: '/downloads/068f46823c14ad9c3b5ef39d0f01f90120210504211103/7924157e91f9eff675d18ac63fcc23b820210504211117/ecbda7',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
} +0ms
  wetransfert:utils getContentInfo: GET https://wetransfer.com/downloads/068f46823c14ad9c3b5ef39d0f01f90120210504211103/7924157e91f9eff675d18ac63fcc23b820210504211117/ecbda7 +4ms
  wetransfert:utils getWetransferPageContent: GET https://wetransfer.com/downloads/068f46823c14ad9c3b5ef39d0f01f90120210504211103/7924157e91f9eff675d18ac63fcc23b820210504211117/ecbda7 +0ms
  wetransfert:utils getContentInfo: sessionCookie, csrf _wt_session=OEhZWDkydU82UjVPSHBMbXc0V2FrdEJhTEh4UGcxUVVwY2lFT040eFZLM1E0NjBmN1BDRXZJTDZhWmtrZzFmMjNFd0wwamswTGhFMzIyTXl4K1lzejltNnZzd29lZVVDbi9ZTDFyWEJENnlnaStBZ1NyYS9UZHI4RXVYWThMMFFtZ1lLekpDYUVBdGN2eFFhT0dKTDRBPT0tLVNIM201RDhyblNrV1R5Snh0NG9Henc9PQ%3D%3D--240381c1bdad5134da088b4c8a5f9ae6c2e5e0c4; domain=wetransfer.com; path=/; secure; HttpOnly; SameSite=Lax hmQfnD7wM3_3xxdGkE-aEHN8mBUhj2nZC9OxiZ4DihsDIXAQbIEuYKdcNF86pxzU4_EGjFXraYqg48eYGd4g0A +525ms
  wetransfert:getinfos security {
  sessionCookie: '_wt_session=OEhZWDkydU82UjVPSHBMbXc0V2FrdEJhTEh4UGcxUVVwY2lFT040eFZLM1E0NjBmN1BDRXZJTDZhWmtrZzFmMjNFd0wwamswTGhFMzIyTXl4K1lzejltNnZzd29lZVVDbi9ZTDFyWEJENnlnaStBZ1NyYS9UZHI4RXVYWThMMFFtZ1lLekpDYUVBdGN2eFFhT0dKTDRBPT0tLVNIM201RDhyblNrV1R5Snh0NG9Henc9PQ%3D%3D--240381c1bdad5134da088b4c8a5f9ae6c2e5e0c4; domain=wetransfer.com; path=/; secure; HttpOnly; SameSite=Lax',
  csrf: 'hmQfnD7wM3_3xxdGkE-aEHN8mBUhj2nZC9OxiZ4DihsDIXAQbIEuYKdcNF86pxzU4_EGjFXraYqg48eYGd4g0A'
} +528ms
  wetransfert:utils formatDownloadApiUri: normal_url +0ms
  wetransfert:getinfos infos { message: 'No download access to this Transfer' } +302ms`
  
  
  Do you have an idea ? I can work on a PR

**Comment by orgrimarr** [comment]
This issue exist since the 2.3.1 release.

The getContentInfos function should use the full body of formatDownloadApiUri function to handle the recipientID present in Nomal url

I release a 2.3.3 version. it should be fixed
