### ISSUE TITLE
trim undefined

### ISSUE THREAD

**Issue by DobleV55** [orgrimarr/node-wetransfert#35]
utils/utils.js:176
from:
`    const csrf = $("meta[name=csrf-token]").attr('content').trim()
`
to:
`
    const csrf = $("meta[name=csrf-token]").attr('content')//.trim()
`
Now csrf value is undefined and works well.

The 'content' attribute doesn't exist anymore, maybe wetransfer remove it. I removed it to test it out, and it works perfectly well.

```
return {
        htmlPage,
        sessionCookie,
        csrf // being undefined it's okay
    }
```

**Comment by DobleV55** [comment]
#36

**Comment by orgrimarr** [comment]
Hi,
Thanks for this fix ! :) 
I will review and merge it tonight after my work
