### ISSUE TITLE
publish on npm registry

### ISSUE THREAD

**Issue by AlexSpelt** [orgrimarr/node-wetransfert#38]
I want to use this package on my node-red server. But node-red can't handle GitHub repositories. Can you publish this package to npm?

**Comment by orgrimarr** [comment]
Hi,
This package is already available as npm package. 

You can have a look a the Readme. 

Here the link : https://www.npmjs.com/package/wetransfert

**Comment by AlexSpelt** [comment]
oh, I didn't see. Sorry.
