### ISSUE TITLE
Issue when passing Base64 encoded file string

### ISSUE THREAD

**Issue by ShadoKima** [orgrimarr/node-wetransfert#6]
When passing a Base64 string into the file path argument, the node module throws an error, I understand my hypothesis was absurd however I was hoping it would be possible. I would like to request this feature (uploading base64 strings) in the near future. Apart from this issue, you have done a marvellous job at creating this module.

**Comment by orgrimarr** [comment]
I'm not sure to fully understand your request :
Did you want instead of uploading a file to upload a string (in your case a base64 string ) ?

Can you give me more information about your use case ?

**Comment by ShadoKima** [comment]
Yes exactly, so instead of specifying a file path to upload, i would like to specify a base64 string. Is that possible?

**Comment by orgrimarr** [comment]
I dont think wetransfer allow text uploading.
A possible workaround would be to write a temp file and then upload it
Or you may use the mail body 

Why do you want to upload a string ?

**Comment by ShadoKima** [comment]
I guess what i'm asking is to be able to pass a file buffer or stream instead of a file path.

**Comment by orgrimarr** [comment]
I agree it would be a nice feature. 
I'll see what I can do.

**Comment by ShadoKima** [comment]
WOW, thank you so much, I am truly grateful, it works perfectly.

**Comment by orgrimarr** [comment]
Cool =)
You can now upgrade your lib : 2.1.0 from NPM
