### ISSUE TITLE
403 with long urls

### ISSUE THREAD

**Issue by lionep** [orgrimarr/node-wetransfert#8]
Hey, nice project there !

If I use a not shortened-url, copied from the receiver mailbox, I get the error :  
```
403 - {"message":"No download access to this Transfer"}
```

Format of the URL : 
```
https://wetransfer.com/downloads/0123456789abcdef0123456789abcdef0123456789abcd/0123456789abcdef0123456789abcdef0123456789abcd/012345
```
of with a company account : 
```
https://mycompany.wetransfer.com/downloads/0123456789abcdef0123456789abcdef0123456789abcd/0123456789abcdef0123456789abcdef0123456789abcd/012345
```

**Comment by orgrimarr** [comment]
Hi, 
Is your wetransfer password protected ?

**Comment by lionep** [comment]
No it’s a simple download, without password.

I can share you a sample link if you need.

**Comment by orgrimarr** [comment]
I'm busy this week-end, 
but yes send me a sample link next week

**Comment by lionep** [comment]
Thanks for your answer, here is a sample link : 
https://wetransfer.com/downloads/b3ce330ccca46e7478f6058e6da7df0c20190318090430/c411c06b12af62fb3741be534e69333f20190318090430/788a94

The code I'm using : 

```javascript
const wt = require('wetransfert');

wt.getInfo('https://wetransfer.com/downloads/b3ce330ccca46e7478f6058e6da7df0c20190318090430/c411c06b12af62fb3741be534e69333f20190318090430/788a94')
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  });
```

**Comment by orgrimarr** [comment]
Ok, 
i found the problem... 
it seems that the upload function does'nt work too.
i wiil fix the upload issue and then publish a new release.

**Comment by orgrimarr** [comment]
wetransfert@2.1.1 available on NPM

[https://www.npmjs.com/package/wetransfert](https://www.npmjs.com/package/wetransfert)
